<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Bondage Club</AssemblyName>
    <RootNamespace>BCDesktop</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>BC Desktop</Product>
    <AssemblyTitle>BC Desktop</AssemblyTitle>
    <Company>BC Client</Company>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishDocumentationFiles>false</PublishDocumentationFiles>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Scripts\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>



</Project>
