<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>BC-Desktop</AssemblyName>
    <RootNamespace>BCDesktop</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>BC Desktop</Product>
    <AssemblyTitle>BC Desktop</AssemblyTitle>
    <Company>BC Client</Company>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app_logo.png" />
  </ItemGroup>

</Project>
